import type { MetadataRoute } from "next";

/**
 * Web app manifest (`/manifest.webmanifest`).
 *
 * Why we ship one even though we're not a true PWA
 * ------------------------------------------------
 * Modern browsers (and Google Search) use the manifest to discover
 * the canonical site name + icon set. Without it, search results
 * can't display the brand name properly and Android's "Add to
 * Home Screen" falls back to a generic icon.
 *
 * `name` here matches the `siteName` in `app/layout.tsx` and the
 * `Organization.name` in the JSON-LD structured data — keeping all
 * three in sync is what tells Google "this site really is called
 * Bravo General Insurance Interface" so the search-result label
 * stops being just the domain.
 */

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Bravo General Insurance Interface",
    short_name: "Bravo GI",
    description:
      "Bravo General Insurance Interface — manage policies, clients, agents, and documents — all in one place.",
    start_url: "/",
    display: "standalone",
    background_color: "#fafafa",
    theme_color: "#171717",
    icons: [
      // `/icon` is generated by `app/icon.tsx` (32x32 square PNG).
      {
        src: "/icon",
        sizes: "32x32",
        type: "image/png",
      },
      // `/apple-icon` is generated by `app/apple-icon.tsx` (180x180).
      // Marked as "any maskable" so Android's adaptive-icon system
      // can crop it cleanly into circles / squircles / teardrops.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any maskable",
      },
    ],
  };
}
